### ISSUE TITLE
tests/test_advanced.py does not run

### ISSUE THREAD

**Issue by vivekaxl** [pooyanjamshidi/GenPerf#1]
```
Traceback (most recent call last):
  File "test_advanced.py", line 3, in <module>
    from context import sample
  File "/Users/viveknair/GIT/GenPerf/tests/context.py", line 7, in <module>
    import sample
ImportError: No module named sample
```

**Comment by pooyanjamshidi** [comment]
Thanks, @vivekaxl, I put the test cases into the `test_basic`, if you have any suggestion for more advanced test cases, please do suggest. This is now fixed.
